apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-instance-status-egress
  namespace: cnpg-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
      app.kubernetes.io/instance: cloudnative-pg
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: platform
          podSelector:
            matchLabels:
              cnpg.io/cluster: platform
      ports:
        - port: 8000
          protocol: TCP
