apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-foundation
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/foundation
  prune: true
  retryInterval: 1m
  serviceAccountName: flux-foundation-reconciler
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-controller
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-foundation
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager-webhook
      namespace: cert-manager
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager-cainjector
      namespace: cert-manager
  interval: 10m
  path: ./infrastructure/cert-manager/controller
  prune: true
  retryInterval: 1m
  serviceAccountName: cert-manager-controller-reconciler
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 15m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-controller
  interval: 10m
  path: ./infrastructure/cert-manager/config
  prune: true
  retryInterval: 1m
  serviceAccountName: cert-manager-config-reconciler
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-controller
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-foundation
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cloudnative-pg
      namespace: cnpg-system
  interval: 10m
  path: ./infrastructure/cnpg/controller
  prune: true
  retryInterval: 1m
  serviceAccountName: cnpg-controller-reconciler
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 15m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-database
  namespace: flux-system
spec:
  dependsOn:
    - name: cnpg-controller
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: platform
      namespace: platform
  interval: 10m
  path: ./infrastructure/cnpg/database
  prune: true
  retryInterval: 1m
  serviceAccountName: flux-platform-database-reconciler
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 20m
  wait: true
