apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - phase-a-rbac.yaml
  - phase-a-network-policy.yaml
images:
  - name: ghcr.io/fluxcd/source-controller
    digest: sha256:c6c82b3182f48b833252c71aefa0741957ca18296612bc6d2b9b5fb276f926e4
  - name: ghcr.io/fluxcd/kustomize-controller
    digest: sha256:3e57aecb74419be93d09ba062cfc882bea405193c474009e0da1826de71a4ebd
  - name: ghcr.io/fluxcd/helm-controller
    digest: sha256:22c0a585d0d9b1f792b9d5638144b7810e273d28e310da37740f01226bd044a2
  - name: ghcr.io/fluxcd/notification-controller
    digest: sha256:cb17eefffbc442412ba6f63336defd04c0fc387d5082d951998d1ff163a9180d
patches:
  - patch: |
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-egress
        namespace: flux-system
      $patch: delete
  - patch: |
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-scraping
        namespace: flux-system
      $patch: delete
  - patch: |
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-webhooks
        namespace: flux-system
      $patch: delete
  - patch: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: crd-controller-flux-system
      $patch: delete
  - patch: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: flux-edit-flux-system
      $patch: delete
  - patch: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: flux-view-flux-system
      $patch: delete
  - patch: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: cluster-reconciler-flux-system
      $patch: delete
  - patch: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: crd-controller-flux-system
      $patch: delete
  - patch: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: flux-system
        labels:
          pod-security.kubernetes.io/audit: restricted
          pod-security.kubernetes.io/audit-version: v1.36
          pod-security.kubernetes.io/enforce: restricted
          pod-security.kubernetes.io/enforce-version: v1.36
          pod-security.kubernetes.io/warn: restricted
          pod-security.kubernetes.io/warn-version: v1.36
  - target:
      kind: Deployment
      name: source-controller
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args/1
        value: --watch-all-namespaces=false
  - target:
      kind: Deployment
      name: kustomize-controller
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args/1
        value: --watch-all-namespaces=false
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --default-service-account=default
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --no-cross-namespace-refs=true
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --no-remote-bases=true
  - target:
      kind: Deployment
      name: helm-controller
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args/1
        value: --watch-all-namespaces=false
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --default-service-account=default
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --no-cross-namespace-refs=true
  - target:
      kind: Deployment
      name: notification-controller
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args/0
        value: --watch-all-namespaces=false
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --no-cross-namespace-refs=true
  - target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: not-used
      spec:
        strategy:
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
          type: RollingUpdate
  - target:
      kind: Deployment
      name: source-controller
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: source-controller
      spec:
        template:
          spec:
            containers:
              - name: manager
                resources:
                  limits:
                    cpu: 400m
                    memory: 512Mi
                  requests:
                    cpu: 100m
                    memory: 256Mi
  - target:
      kind: Deployment
      name: kustomize-controller
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: kustomize-controller
      spec:
        template:
          spec:
            containers:
              - name: manager
                resources:
                  limits:
                    cpu: 1000m
                    memory: 1Gi
                  requests:
                    cpu: 250m
                    memory: 512Mi
  - target:
      kind: Deployment
      name: helm-controller
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: helm-controller
      spec:
        template:
          spec:
            containers:
              - name: manager
                resources:
                  limits:
                    cpu: 400m
                    memory: 512Mi
                  requests:
                    cpu: 100m
                    memory: 256Mi
  - target:
      kind: Deployment
      name: notification-controller
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: notification-controller
      spec:
        template:
          spec:
            containers:
              - name: manager
                resources:
                  limits:
                    cpu: 200m
                    memory: 256Mi
                  requests:
                    cpu: 50m
                    memory: 128Mi
