apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate.yaml
  - helmrelease.yaml
  - network-policy.yaml
  - probe.yaml
  - resourcequota.yaml
configMapGenerator:
  - files:
      - values.yaml
    name: openbao-helm-values
    namespace: flux-system
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: engineering-platform
    platform.unif.internal/environment: dev
