#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
RECOVERY_HOME="${OPENBAO_RECOVERY_HOME:-$HOME/OpenBao-Recovery}"
OPENBAO_GPG_FINGERPRINT=""
wizard_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
readonly OPENBAO_RECOVERY_HELPER="${wizard_dir}/../bootstrap/lib/openbao_recovery.py"

copy_recovery_item_to_clipboard() {
  local archive=$1 expected_schema=$2 item=$3
  [[ -f "$OPENBAO_RECOVERY_HELPER" ]] || {
    warn "未找到恢复包校验工具；请在仓库根目录重新运行向导"
    return 1
  }
  # PowerShell expands $plain inside its own process.
  # shellcheck disable=SC2016
  python "$OPENBAO_RECOVERY_HELPER" emit-item \
    --archive "$archive" --sidecar "${archive}.sha256" \
    --expected-schema "$expected_schema" --item "$item" |
    base64 --decode |
    gpg --decrypt |
    powershell.exe -NoProfile -NonInteractive -Command \
      '$plain = [Console]::In.ReadToEnd(); Set-Clipboard -Value $plain'
}

banner "DEV OpenBao 恢复仪式"

stage "Gpg4win / GnuPG"
say "本向导只在 Windows Git Bash 运行；绝不读取私钥或口令。"
if ! command -v gpg >/dev/null 2>&1; then
  open_url "https://www.gpg4win.org/get-gpg4win.html"
  step "从官方页面安装 Gpg4win（含 GnuPG），随后重新打开 Git Bash。"
  pause "确认 gpg 已安装后按 Enter。"
fi
command -v gpg >/dev/null 2>&1 || { warn "gpg 仍不可用"; exit 1; }
printf "%b\n" "${RED}敏感仪式：${RESET}绝不把明文粘贴到此 shell。"
say "Gpg4win / GnuPG 已就绪。"

stage "专用恢复密钥"
say "使用受 GPG pinentry 保护的专用密钥；口令始终只留在 pinentry。"
if ! confirm "是否复用已有的专用 OpenBao 恢复密钥？"; then
  step "执行 gpg --full-generate-key，并仅在 pinentry 中完成提示。"
  gpg --full-generate-key
fi
gpg --list-secret-keys --keyid-format long
ask OPENBAO_GPG_FINGERPRINT "输入专用密钥 fingerprint（公开值）："
OPENBAO_GPG_FINGERPRINT=${OPENBAO_GPG_FINGERPRINT//[[:space:]]/}
[[ "$OPENBAO_GPG_FINGERPRINT" =~ ^[0-9A-Fa-f]{40}$|^[0-9A-Fa-f]{64}$ ]] || {
  warn "fingerprint 必须是 40 或 64 位十六进制字符"
  exit 1
}
OPENBAO_GPG_FINGERPRINT=${OPENBAO_GPG_FINGERPRINT^^}
gpg --batch --list-secret-keys "$OPENBAO_GPG_FINGERPRINT" >/dev/null

stage "仅导出公钥"
say "只导出 base64 公钥和公开 fingerprint。"
mkdir -p "$RECOVERY_HOME"
chmod 700 "$RECOVERY_HOME"
public_key="$RECOVERY_HOME/openbao-recovery-public-key.b64"
fingerprint_file="$RECOVERY_HOME/openbao-recovery-public-key.fingerprint"
public_tmp=$(mktemp "$RECOVERY_HOME/.public-key.XXXXXX")
fingerprint_tmp=$(mktemp "$RECOVERY_HOME/.fingerprint.XXXXXX")
gpg --batch --export "$OPENBAO_GPG_FINGERPRINT" | base64 | tr -d '\r\n' >"$public_tmp"
printf '\n' >>"$public_tmp"
printf '%s\n' "$OPENBAO_GPG_FINGERPRINT" >"$fingerprint_tmp"
chmod 600 "$public_tmp" "$fingerprint_tmp"
if [[ -e "$public_key" || -e "$fingerprint_file" ]]; then
  if ! cmp -s "$public_tmp" "$public_key" ||
      ! cmp -s "$fingerprint_tmp" "$fingerprint_file"; then
    rm -f -- "$public_tmp" "$fingerprint_tmp"
    warn "existing public-key files differ; nothing was overwritten"
    exit 1
  fi
  rm -f -- "$public_tmp" "$fingerprint_tmp"
else
  mv "$public_tmp" "$public_key"
  mv "$fingerprint_tmp" "$fingerprint_file"
fi
say "公钥：$public_key"
say "Fingerprint：$OPENBAO_GPG_FINGERPRINT"
step "仅将这两个公开文件上传到服务器 /root/.config/engineering-platform。"

stage "密文恢复包与剪贴板"
say "将服务器生成的 recovery .tar.gz 及其 .sha256 下载到 $RECOVERY_HOME。"
ask RECOVERY_ARCHIVE "已下载 recovery .tar.gz 的路径："
[[ -f "$RECOVERY_ARCHIVE" && -f "${RECOVERY_ARCHIVE}.sha256" ]] || {
  warn "缺少 archive 或 checksum sidecar"
  exit 1
}
(cd "$(dirname "$RECOVERY_ARCHIVE")" && sha256sum -c "$(basename "$RECOVERY_ARCHIVE").sha256")
RECOVERY_SCHEMA=$(python "$OPENBAO_RECOVERY_HELPER" verified-schema \
  --archive "$RECOVERY_ARCHIVE" --sidecar "${RECOVERY_ARCHIVE}.sha256") || {
  warn "恢复包未通过完整 schema 校验"
  exit 1
}
say "已由校验通过的恢复包读取 schema：$RECOVERY_SCHEMA"
case "$RECOVERY_SCHEMA" in
  engineering-platform/openbao-recovery/v1)
    say "本次恢复可从已校验旧包选择三份不同的有效旧 share，无需识别泄露编号；仅在对应隐藏提示中粘贴。"
    RECOVERY_ITEM_PROMPT='要解密到剪贴板的项目（share1..share5 或 root）：'
    ;;
  engineering-platform/openbao-recovery-rotation-candidate/v1)
    RECOVERY_ITEM_PROMPT='要解密到剪贴板的新 share（share1..share5）：'
    ;;
  engineering-platform/openbao-recovery/v2)
    RECOVERY_ITEM_PROMPT='要解密到剪贴板的新 share（share1..share5）：'
    ;;
  *)
    warn "恢复包 schema 不受支持"
    exit 1
    ;;
esac
ask RECOVERY_ITEM "$RECOVERY_ITEM_PROMPT"
case "$RECOVERY_SCHEMA:$RECOVERY_ITEM" in
  engineering-platform/openbao-recovery/v1:share[1-5]|engineering-platform/openbao-recovery/v1:root|engineering-platform/openbao-recovery-rotation-candidate/v1:share[1-5]|engineering-platform/openbao-recovery/v2:share[1-5]) ;;
  *)
    warn "该 schema 仅允许选择规定的恢复项目"
    exit 1
    ;;
esac
copy_recovery_item_to_clipboard \
  "$RECOVERY_ARCHIVE" "$RECOVERY_SCHEMA" "$RECOVERY_ITEM" || {
  warn "恢复包未通过校验，或该项目不被该 schema 允许"
  exit 1
}
say "已选明文只存在于 Windows 剪贴板；不会打印或落盘。"

stage "隐藏提示、服务器仪式与清理"
step "服务器操作仅能在外部 Chrome 的最新 Web终端 - 统一企业堡垒机 标签页执行；不得使用 SSH、应用内浏览器或本地终端。"
case "$RECOVERY_SCHEMA" in
  engineering-platform/openbao-recovery/v1)
    step "这是事故 v1 恢复，不是正常 v1 configure 路径；不得跳步或改用 configure。"
    step "先按 runbook 运行带 source SHA 的只读 check；收到预期 readback 后才运行 recover-start。"
    step "从已校验旧包选择三份不同的有效旧 share，无需识别泄露编号；逐份粘贴到三个隐藏 unseal prompt。"
    step "随后旧 share 轮换授权也需三份不同的有效旧 share，可复用刚才三份；不要把同一份重复当作三份。"
    step "verification 成功前不能宣称旧份额失效；保留旧恢复包和 GPG 私钥，不重新初始化或删除 PVC。"
    step "只有出现隐藏 root-token prompt 时才选择 root；绝不把它输入命令行、聊天或普通 shell。"
    ;;
  engineering-platform/openbao-recovery-rotation-candidate/v1)
    step "候选恢复包尚未完成验证，不是最终恢复包；仅解密三份新 share。"
    step "在收到候选包下载/sidecar 校验成功的回执后，按 runbook 运行 recover-verify。"
    ;;
  engineering-platform/openbao-recovery/v2)
    step "初始 root token 已撤销；v2 只允许新 share，不能选择 root。"
    step "确认最终 v2 密文恢复包及其 checksum 已上传到受控云存储。"
    confirm "确认最终 v2 密文包与 checksum 已上传到受控云存储？" || {
      warn "cloud 上传尚未完成"
      exit 1
    }
    say "现在执行 Clear-Clipboard 安全步骤。"
    # PowerShell expands $null inside its own process.
    # shellcheck disable=SC2016
    powershell.exe -NoProfile -NonInteractive -Command 'Set-Clipboard -Value $null'
    say "剪贴板已清空。私钥和口令必须与云端密文包分离保存。"
    ;;
esac
say "source/candidate 恢复包清理需要单独的明确批准；本向导不会删除任何恢复材料。"

finish
