#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
RECOVERY_HOME="${OPENBAO_RECOVERY_HOME:-$HOME/OpenBao-Recovery}"
OPENBAO_GPG_FINGERPRINT=""

copy_recovery_item_to_clipboard() {
  local archive=$1 item=$2
  # PowerShell expands $plain inside its own process.
  # shellcheck disable=SC2016
  tar -xOf "$archive" --wildcards '*/init.json' |
    python -c '
import json
import sys

item = sys.argv[1]
document = json.load(sys.stdin)
if item == "root":
    value = document.get("root_token")
elif item.startswith("share") and item[5:].isdigit():
    index = int(item[5:]) - 1
    keys = document.get("unseal_keys_b64", [])
    value = keys[index] if 0 <= index < len(keys) else None
else:
    value = None
if not isinstance(value, str) or len(value) < 100:
    raise SystemExit(1)
sys.stdout.write(value)
' "$item" |
    base64 --decode |
    gpg --decrypt |
    powershell.exe -NoProfile -NonInteractive -Command \
      '$plain = [Console]::In.ReadToEnd(); Set-Clipboard -Value $plain'
}

banner "DEV OpenBao recovery ceremony"

stage "Gpg4win / GnuPG"
say "This wizard runs on Windows Git Bash and never captures a private key or passphrase."
if ! command -v gpg >/dev/null 2>&1; then
  open_url "https://www.gpg4win.org/get-gpg4win.html"
  step "Download Gpg4win from the official page, install GnuPG, then reopen Git Bash."
  pause "Press Enter after gpg is installed."
fi
command -v gpg >/dev/null 2>&1 || { warn "gpg is still unavailable"; exit 1; }
printf "%b\n" "${RED}Sensitive ceremony:${RESET} never paste plaintext into this shell."
say "Gpg4win / GnuPG is ready."

stage "Dedicated recovery key"
say "Use a dedicated key protected by GPG pinentry. The passphrase stays in pinentry."
if ! confirm "Reuse an existing dedicated OpenBao recovery key?"; then
  step "Run gpg --full-generate-key and complete the pinentry prompts."
  gpg --full-generate-key
fi
gpg --list-secret-keys --keyid-format long
ask OPENBAO_GPG_FINGERPRINT "Paste the dedicated key fingerprint (public):"
OPENBAO_GPG_FINGERPRINT=${OPENBAO_GPG_FINGERPRINT//[[:space:]]/}
[[ "$OPENBAO_GPG_FINGERPRINT" =~ ^[0-9A-Fa-f]{40}$|^[0-9A-Fa-f]{64}$ ]] || {
  warn "fingerprint must be 40 or 64 hexadecimal characters"
  exit 1
}
OPENBAO_GPG_FINGERPRINT=${OPENBAO_GPG_FINGERPRINT^^}
gpg --batch --list-secret-keys "$OPENBAO_GPG_FINGERPRINT" >/dev/null

stage "Export public key only"
say "Only a base64-encoded public key and its public fingerprint are exported."
mkdir -p "$RECOVERY_HOME"
chmod 700 "$RECOVERY_HOME"
public_key="$RECOVERY_HOME/openbao-recovery-public-key.b64"
fingerprint_file="$RECOVERY_HOME/openbao-recovery-public-key.fingerprint"
public_tmp=$(mktemp "$RECOVERY_HOME/.public-key.XXXXXX")
fingerprint_tmp=$(mktemp "$RECOVERY_HOME/.fingerprint.XXXXXX")
gpg --batch --export "$OPENBAO_GPG_FINGERPRINT" | base64 | tr -d '\r\n' >"$public_tmp"
printf '\n' >>"$public_tmp"
printf '%s\n' "$OPENBAO_GPG_FINGERPRINT" >"$fingerprint_tmp"
chmod 600 "$public_tmp" "$fingerprint_tmp"
if [[ -e "$public_key" || -e "$fingerprint_file" ]]; then
  if ! cmp -s "$public_tmp" "$public_key" ||
      ! cmp -s "$fingerprint_tmp" "$fingerprint_file"; then
    rm -f -- "$public_tmp" "$fingerprint_tmp"
    warn "existing public-key files differ; nothing was overwritten"
    exit 1
  fi
  rm -f -- "$public_tmp" "$fingerprint_tmp"
else
  mv "$public_tmp" "$public_key"
  mv "$fingerprint_tmp" "$fingerprint_file"
fi
say "Public key: $public_key"
say "Fingerprint: $OPENBAO_GPG_FINGERPRINT"
step "Upload these two public files to /root/.config/engineering-platform on the server."

stage "Ciphertext bundle and clipboard"
say "Download the server-produced recovery .tar.gz and .sha256 into $RECOVERY_HOME."
ask RECOVERY_ARCHIVE "Path to the downloaded recovery .tar.gz:"
[[ -f "$RECOVERY_ARCHIVE" && -f "${RECOVERY_ARCHIVE}.sha256" ]] || {
  warn "archive or checksum sidecar is missing"
  exit 1
}
(cd "$(dirname "$RECOVERY_ARCHIVE")" && sha256sum -c "$(basename "$RECOVERY_ARCHIVE").sha256")
ask RECOVERY_ITEM "Item to decrypt to clipboard (share1..share5 or root):"
[[ "$RECOVERY_ITEM" =~ ^share[1-5]$|^root$ ]] || {
  warn "item must be share1..share5 or root"
  exit 1
}
copy_recovery_item_to_clipboard "$RECOVERY_ARCHIVE" "$RECOVERY_ITEM"
say "The selected plaintext exists only in the Windows clipboard; it was not printed or saved."

stage "Hidden prompts, cloud upload, cleanup"
step "In the approved bastion terminal, run Stage 180 --configure."
step "Use the prior stage repeatedly to paste three unseal shares into the three hidden prompts."
step "Then decrypt root and paste it only into the hidden root-token prompt; Stage 180 revokes it."
step "Upload the ciphertext .tar.gz and .sha256 to your controlled cloud drive."
confirm "Confirm the ciphertext bundle and checksum are safely uploaded to cloud storage." || {
  warn "cloud upload remains incomplete"
  exit 1
}
say "Running the Clear-Clipboard safety step now."
# PowerShell expands $null inside its own process.
# shellcheck disable=SC2016
powershell.exe -NoProfile -NonInteractive -Command 'Set-Clipboard -Value $null'
say "Clipboard cleared. Keep the private key and passphrase separate from the cloud bundle."

finish
