apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend
  namespace: platform
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend
  namespace: platform
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
