apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-accounts.yaml
  - frontend-config.yaml
  - frontend.yaml
  - backend.yaml
  - services.yaml
  - http-route.yaml
  - disruption-budgets.yaml
  - network-policy.yaml
