apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: platform
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: platform
automountServiceAccountToken: false
